name: todolistapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_cupernino_bottom_sheet: ^1.0.8
  animated_slide_switcher: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/png/profile.png


  fonts:
    - family: sfBold
      fonts:
        - asset: assets/font/sf/bold.otf
    - family: sfMedium
      fonts:
        - asset: assets/font/sf/medium.otf
    - family: sfRegular
      fonts:
        - asset: assets/font/sf/regular.otf